name: openiam-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push openiam Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: Web/Dockerfile
        push: true
        tags: stg609/openiam:v1.7.${{ github.run_number }}
        
    - name: Deploy To Aliyun
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.ALIYUN_SSH_HOST }}
        username: ${{ secrets.ALIYUN_SSH_USERNAME }}
        password: ${{ secrets.ALIYUN_SSH_PASSWORD }}
        port: ${{ secrets.ALIYUN_SSH_PORT }}
        script: |
            docker pull stg609/openiam:v1.7.${{ github.run_number }}
            docker stop openiam
            docker run -d --name openiam -p 5000:80 -v /root/projects/openiam/appsettings.json:/app/appsettings.json -v /root/projects/openiam/logs:/app/logs -e Certificate__Path=lics/idsrv4.pfx -e ASPNETCORE_ENVIRONMENT=Production -e "ASPNETCORE_URLS=http://+:80;" stg609/openiam:v1.7.${{ github.run_number }}

