name: openiam-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push openiam Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: Web/Dockerfile
        push: true
        tags: stg609/openiam:v1.7.${{ github.run_number }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
